# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbmFit <- function(edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights, tolerance, seedComms) {
    .Call('_sbmt_sbmFit', PACKAGE = 'sbmt', edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights, tolerance, seedComms)
}

sbmtFit <- function(edgelistTime, maxComms, directed, klPerNetwork, degreeCorrect, nodes, tolerance, seedComms) {
    .Call('_sbmt_sbmtFit', PACKAGE = 'sbmt', edgelistTime, maxComms, directed, klPerNetwork, degreeCorrect, nodes, tolerance, seedComms)
}

