// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sbmFit
List sbmFit(const IntegerMatrix& edgelist, const int maxComms, const int degreeCorrect, const bool directed, const int klPerNetwork, const NumericVector weights);
RcppExport SEXP sbm_sbmFit(SEXP edgelistSEXP, SEXP maxCommsSEXP, SEXP degreeCorrectSEXP, SEXP directedSEXP, SEXP klPerNetworkSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type edgelist(edgelistSEXP);
    Rcpp::traits::input_parameter< const int >::type maxComms(maxCommsSEXP);
    Rcpp::traits::input_parameter< const int >::type degreeCorrect(degreeCorrectSEXP);
    Rcpp::traits::input_parameter< const bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< const int >::type klPerNetwork(klPerNetworkSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(sbmFit(edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights));
    return rcpp_result_gen;
END_RCPP
}
