# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbmFit <- function(edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights, tolerance) {
    .Call('_sbm_sbmFit', PACKAGE = 'sbm', edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights, tolerance)
}

sbmtFit <- function(edgelistTime, maxComms, directed, klPerNetwork, degreeCorrect, nodes, tolerance) {
    .Call('_sbm_sbmtFit', PACKAGE = 'sbm', edgelistTime, maxComms, directed, klPerNetwork, degreeCorrect, nodes, tolerance)
}

