# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sbmFit <- function(edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights) {
    .Call('sbm_sbmFit', PACKAGE = 'sbm', edgelist, maxComms, degreeCorrect, directed, klPerNetwork, weights)
}

